### ISSUE TITLE
Confidence score for translation

### ISSUE THREAD

**Issue by davidecaroselli** [modernmt/modernmt#437]
We want to include a "confidence" score together with the translation.
This score will measure not the translation quality directly, but the "confidence" of the system in outputting the translation.

Open challenges:

- We want this number be normalized `[0, 1]`
- We expect this score to be better if the model has been adapted. Running a quick training on very similar content should reduce the perplexity of the system.
- We have to measure a sort of correlation between this score and the actual translation quality in both static and adaptive scenario.

**Comment by davidecaroselli** [comment]
An update on this topic.

We have been experimenting with the **perplexity** value returned with the translation. This is in fact the score used in the beam search to choose the best translation, so ideally it is good starting point.

The results are a bit misleading however. The perplexity in fact measure how "hard" was to translate a sentence, it does indicate nothing about the output quality, or the expected output quality (what we intend for confidence).

The result is that perfectly good translations have not-too-high score, while very odd sentences return the best results. Let me show some examples:

```
SRC: This is just an example
TRN: Questo è solo un esempio
SCORE: 0.72

SRC: When you run the program , the output will be :
TRN: Quando si esegue il programma , l' output sarà :
SCORE: 0.80
```

Those are two good italian translations, however if we provide some very odd sentences like the following:

```
SRC: rvibpib
TRN: rvibpib
SCORE: 0.94

SRC: junkyjunkyjunky
TRN: junkyjunkyjunky
SCORE: 0.87
```

They have a score as high or even much better than an actual translation.
One last example, these are two very good translations for a tough source sentence. They should have a high score, instead...

```
SRC: Thou shall not pass
TRN: Tu non passerai
SCORE: 0.48

SRC: Leave
TRN: Esci
SCORE: 0.31
```

The last example shows exactly the problem with perplexity: "Esci" is perfect, the problem is that "Leave" is a too generic word and the model is really undecided on which word to use.
Not sure if this was what we want.

**Comment by EtienneAb3d** [comment]
It's seems ok for me like this. It's a confidence score, not a quality estimation. 
But, as said above, I think the global score is of poor interest, while a word by word, or token by token, estimation would be very informative: it would enable to know the words where there are possible alternatives to build a different sentence, thus having certainly a different meaning.

**Comment by kkosmaczewska** [comment]
It seems that the way it's working now the confidence score might be misleading. I am unable to offer a better alternative at this point in time but I am an not sure how helpful the score would be if it is quite low for good translation results.
Perhaps it might be worth looking into quality estimation instead.

**Comment by davidecaroselli** [comment]
Hi @kkosmaczewska ,

I agree with you: the way this score works is not exactly what we would like to achieve, and probably the right option to achieve a "expected quality" score is to setup a quality estimation tool (just like the one you suggested on the email).
The problem is that such tool is a distinct tool from what ModernMT is; it has its own models, runtime dependency and hardware requirements.

**Comment by davidecaroselli** [comment]
A final conclusion to this topic: because the score as it is from fairseq does not match our expectations, we decided to not include this value in the API because the results could be misleading.

The score is however still available at lower level (Java/Python interface) in order to support future development or allow our users to customize ModernMT including somehow this score.

Thanks all for the support!

**Comment by mzeidhassan** [comment]
I am sorry @davidecaroselli to reopen this. Please accept my apology. 

I think this is a very interesting feature to have. As far as I understand, it seems it was very consistent to get really high confidence score/perplexity value for really odd sentences as you have shown above.  If this is consistent, although it doesn't make sense in terms of score "higher here is worse, not better", then can't we use this score to mark strings for human post-editing? Have you experimented with this? Does this make sense?

One last question:
Any idea how I can include this back in the API output? 

Thanks and sorry again for re-opening this issue.

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

no problem into re-opening a closed issue! :)

> If this is consistent, although it doesn't make sense in terms of score "higher here is worse, not better", then can't we use this score to mark strings for human post-editing?

Unfortunately this is not the case. The problem is that there is no strong correlation between translation quality and confidence score, that was indeed the real problem.
In my examples I show how very odd sentences get a very high score, but the problem is that even very good translations have a high score. So the problem is that we are unable to understand if the score is low because a translation was "difficult" or if it's "horrible" and viceversa.

**Comment by bittlingmayer** [comment]
Interesting to see your experiences with Fairseq and the glassbox approach.

Agree with the comments above, *rvibpib* is basically a translingual symbol, on the other hand the low confidence for *Leave* is also expected, because it's actually super ambiguous (*lasciare, lasci, lasciate, uscire, esci, uscite, partire, ..., abbandonare, congedo...*).

In the WMT workshop, the QE task optimises for human edit distance (HTER).  The problem with this is that stylistic tweaks can change lots of chars, whereas fixing a very bad error - like *43* → *42*, missing negation or an offensive word - may be a minor edit.

Do you have a solution to this, do you know yet what you're optimising for?  And how do the scores you see correlate with input length?  Are they somehow implicitly normalised, ie if the sentence is very long, does an error count for less?

**Comment by bittlingmayer** [comment]
Update for those who don't know: ModelFront is now offering machine translation quality prediction ("quality estimation" in the research world).

https://modelfront.com/
https://modelfront.com/docs/api/

It's engine-independent ("blackbox") - you pass the original text and the translation text - and of course TMS-independent and LSP-independent.

(Just as a convenience, you can also call it with just the original text and have it filled in by one of the top machine translation APIs, including ModernMT, including custom engines.)

It returns a quality score from 0.0 to 1.0.  It supports all languages ModernMT supports and more, and is customizable on your data - the key to getting human parity, in our experience.
