### ISSUE TITLE
NeuroSpell : neural spell checker + neural MT

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#443]
Just to let you know what I'm currently experimenting...
I built a neural spell checker. Even in the very first version, I obtain very incredible results.
The spell checker is linked with an automatic translator, to translate the corrected texts.
Both made with MMT, powered by its great live-tuning feature !
http://neurospell.com/
Thanks to the MMT team !
:+1:

**Comment by mzeidhassan** [comment]
You are awesome @EtienneAb3d ! Congratulations! 

Any chance you can share what you did in terms of the neural spell-checker. What data did you need to feed? Do you simply train as you do with the neural machine translation part and the only difference is the data input? Thanks in advance!

**Comment by EtienneAb3d** [comment]
Hmmm.. as this spell checker is the first I know using a neural net, I prefer to keep the recipe for me at this time, and see what will come with it. 
Perhaps I will explain it later, in a near future. Be sure this place will certainly be the first to know.
What I can say is that the method is very simple.
;-)

**Comment by nonsequitir** [comment]
There are SO MANY applications for this (inbound data cleansing comes to mind). Looking forward to see this evolve!  Nice work.

**Comment by EtienneAb3d** [comment]
As far as I know, this is the very first "spell corrector", while all others are only "spell checkers". 
Spell checkers  often leave the user with highlighted doubts, and rules to be decided. But, a bad, or very bad, writer often don't know what to do with the provided rules. It was my case when I was younger !
NeuroSpell directly show the correction of the text entered, with a high capability to be accurate (even in this very first version). 
More than this, ordinary spell checkers are quickly lost when the writer is an awful one, like what we see in the social networks, while NeuroSpell can fix even the harder (be not all kind of errors).

**Comment by nonsequitir** [comment]
Is there a date for availability of this tool?  Would LOVE to test it :)

**Comment by EtienneAb3d** [comment]
A link to the first french very is provided above, in the first post. You can test it here. Of course, to test pertinent entries, you will need to know the usual kind of errors of french writers.
http://neurospell.com
A new release of this french version is in preparation.
An english one will come quickly.

**Comment by EtienneAb3d** [comment]
The very first english version is inline:
http://neurospell.com/en.php
There is a lot to do to improve. But, here is an example of what it can do:
![image](https://user-images.githubusercontent.com/25932245/53025307-fb5a1380-3460-11e9-8787-b7d7914273c1.png)

**Comment by EtienneAb3d** [comment]
Just a remark : this tool is made for human writers, if you would like to evaluate its behaviour, it's better to enter some texts that would be human-plausible. :-)

**Comment by mzeidhassan** [comment]
I tested it with this sentence "The naturel couse of thes crisi will end son.". I am not sure if it's human-plausible or not :-) 

You can see the result in the screen shot. 

![image](https://user-images.githubusercontent.com/7589948/53038636-765c0380-343a-11e9-9d8e-2d1c990792ea.png)

**Comment by EtienneAb3d** [comment]
I think that, usually, a human, especially native for the language, when really trying to write a sentence, won't try to write something being not phonetically almost correct. There are already so much ways to write something wrong but phonetically almost correct...
In your case, if you read your wrong words, you won't get something really understandable.
"naturel" is perhaps a word that could have been plausible. I will improve for such a case.
;-)

**Comment by EtienneAb3d** [comment]
For example:
![image](https://user-images.githubusercontent.com/25932245/53039777-3750a100-3480-11e9-8004-72622adff684.png)
Experimenting with your example, I notice that "son" wouldn't be corrected, certainly because a real word. Note: this MMT model is at early stage of the training, possibly it will more efficient with more training time.

**Comment by mzeidhassan** [comment]
It looks good and promising. I was just testing it and sharing with you what I found so you can improve it :-)

**Comment by EtienneAb3d** [comment]
![image](https://user-images.githubusercontent.com/25932245/53041249-c9a67400-3483-11e9-988c-6f708e0db25e.png)

**Comment by EtienneAb3d** [comment]
Oops.. I didn't see that the "end" wasn't correct in the latest version of my sentence, while it was in the previous one. Not perfect..

**Comment by EtienneAb3d** [comment]
Note how "while" is changed in "will" when "is" is changed in "be", and with "?" at the end:
![image](https://user-images.githubusercontent.com/25932245/53041718-f9a24700-3484-11e9-8daa-d1a248914696.png)
(I also removed "the" that was an extra word lost by error in my attempts)

**Comment by oytuntez** [comment]
@EtienneAb3d thanks for the demo. I think you may have some insights about my question here: https://github.com/modernmt/MMT/issues/448

Would you mind taking a look?

**Comment by EtienneAb3d** [comment]
NeuroSpell is now an hybrid system, combining a ModernMT neural network, with a lexical search, a POS-tagger, grammar rules, and a statistical model. I wrote a short explanation on how NeuroSpell is working, here (see "How does it work ?" button):
http://neurospell.com/en.php
Also available in french, here:
http://neurospell.com
ModernMT is quoted in these explanations, like on the main web page.
Thanks to the MMT team for making all this possible !

**Comment by Hasan0ff** [comment]
@EtienneAb3d would you mind sharing the code for spell checker if its open source? Moreover, can you tell me the specs for the server you use to run neurospell (gpu, cpu and ram)?

**Comment by EtienneAb3d** [comment]
@Hasan0ff, NeuroSpell is using ModernMT and LanguareTool, both open-source, but for the moment, is not open-source itself. It uses proprietary code.
It's free to use using its web interface, and will certainly stay free for this kind of access.
It's written in Java. It's currently running on a Linux machine, and does not need large CPU, nor large RAM. ModernMT is running on a GTX 1080 Ti card.
If you want, it can be trained/tuned on your own data.
It uses a Java XML-RPC server, with an API I can share (not free). 
I can install all on your own server for a private secure use (not free).
As said above, you will find some minimal explanations on the way it's working on the web site. 
;-)

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

thanks for having shared this, and compliments for the great job! :)

**Comment by EtienneAb3d** [comment]
Version 1.0 beta of NeuroSpell for English is online.

Perhaps some of you may be interested in this kind of **automatic** corrections:
![CambridgeEN](https://user-images.githubusercontent.com/25932245/141966791-83e41192-fe57-4690-a236-a05144d32d1d.png)

![CambridgeEN2](https://user-images.githubusercontent.com/25932245/141966807-aa63a3d8-e482-4b3d-8d5a-d3da77ea9dcf.png)

V1 for French and V0 for Spanish are in preparation.

Then, I will release a version for a new language every 10-15 days. I hope to be able provide with all 24 EU languages for the beginning of 2022.

Thanks to ModernMT team that enables this to exist!

**Comment by mzeidhassan** [comment]
Thanks @EtienneAb3d for keeping this issue updated! This looks super cool. I hope all is well with you. 
Good luck!
