### ISSUE TITLE
context_vector : how to control the live-tuning effect ?

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#450]
When I'm changing the context_vector parameter, I see that this has an effect on the tuning. 
But, even with very low values, even with value 0.0, the tuning always seems to stay quite high.
Can you explain how this is working, and how I may adapt the live-tuning effect to a lower value ?

**Comment by EtienneAb3d** [comment]
Found! I changed the addition to a product in both rescoring files, and this is now doing exactly what I expected: a finer control over the live-tuning effect!
![image](https://user-images.githubusercontent.com/25932245/53558149-b52f3f00-3b47-11e9-8c0c-ead8d9bf6f38.png)

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

the previous version was made for avoid too-low scores that could result in poor adaptation. This really depends on the use case: what works in a standard translation task, could be the sub-optimal solution for another task.

Thanks for having shared this!
