### ISSUE TITLE
Memory issues?

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#451]
When I load multiple memories at the same time, the third/fourth memory or so gets stuck at Loading models...

Is this because I do not have enough memory? I currently have 16 GB in this machine.

**Comment by LoekvanKooten** [comment]
@davidecaroselli Help?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
sorry for the late answer,

very likely, the problem is that you are trying to upload your memories at the same time
and so there is a lot of concurrency when they are written on the DB.

Moreover, while uploading the TM, the CPU is used.
Hence, there is the risk that you run out of memory if your TMs are big and/or you upload multiple TMs.

So I strongly suggest to upload the TMs sequentially.

**Comment by LoekvanKooten** [comment]
Noob alert! Is there a batch command that makes sure it does not execute the next command until the previous command is completely finished? As I think that they are being uploaded one by one in a batch file.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
which is the command you used?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

Actually the standard command to import a TM is using a command like this:
````
mmt import -e ENGINE -x TMX
```
this command show a progress bar.
When it reaches 100%, the import job is completed.

And you can safely start a new import

**Comment by LoekvanKooten** [comment]
This is my current batch:

`echo "Starting Tensorflow..."
cd
test_function() { . $HOME/anaconda2/bin/activate; }
test_function tensorflow
echo "Starting ModernMT with verbose log..."
cd mmt7
./mmt stop -e engdut
./mmt stop -e engjap
./mmt stop -e japeng
./mmt stop -e japdut
./mmt start -e engdut -v 2
./mmt start -e engjap -p 8048 --cluster-port 5019 --datastream-port 9095 --db-port 9045 -v 2
./mmt start -e japeng -p 8049 --cluster-port 5020 --datastream-port 9096 --db-port 9046 -v 2
./mmt start -e japdut -p 8046 --cluster-port 5017 --datastream-port 9093 --db-port 9043 -v 2
exec bash
~           `

**Comment by LoekvanKooten** [comment]
Everything goes well, until the last one (japdut) is started. It gets stuck at Loading models, but not consistently. Sometimes it does load the model in its entirety.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
probably I did not get  your get your problem.

Are you starting 4 different engines, each one handling one language?
or rather
are you interesting in uploading multiple translation memories in the same engine?

please clarify your scenario in order to let me help in the best way.

By the way, if you are using four different engine at the same time, it is very likely that you ran out of GPU memory. you can monitor the GPU RAM using the command 
```
nvidia-smi
```

**Comment by LoekvanKooten** [comment]
I'm indeed trying to serve four memories simultaneously (as I switch language ;pairs constantly on a day). How would I solve the memory issue? Place a 2nd graphics card? Would that also speed up the suggestions?

**Comment by nicolabertoldi** [comment]
have you trying the multilingual facility of ModernMT
As you can see in this page https://github.com/modernmt/MMT/wiki/Multilingual-Engines
*Starting from release 2.0, ModernMT supports multilingual engines. This means that you can use a single ModernMT system to handle multiple language directions.*

This allows having more languages without GPU memory problems, even with just one GPU on board.

As you can read in the instructions, there is no need to re-train the single-language engines.
Please follow carefully the instructions to build a "multilingual engine", and report if you succeeds.

**Comment by LoekvanKooten** [comment]
Thank you very much! That sounds like an interesting option. I just loaded four memories by the way, and am only using 6 out of 12 MiB. So I wonder whether memory is the real issue. I'll run the nvidia-smi command again once the engines get stuck again.

Would a 2nd card speed up suggestions by the way? And if so, would I need the same make/model?

**Comment by nicolabertoldi** [comment]
I would suggest to monitor continuously both the GPU and the CPU usage for instance using
```watch nvidia-smi```
and 
```watch free -h```
which print =s statistics every few seconds.


Having a 2 GPU permits to split the load on the two GPUS. 
If you have 4 engines, you should specify two engines on GPU A and two engines on GPU B as explained here
https://github.com/modernmt/MMT/wiki/Advanced-Configurations#engine-configuration

But it is better to understand if your OOM on the GPU is occurring during the uploading of the memories or rather during the translation.
I would suggest first of all to test the engines without memories trying to translate a bunch of queries for all languages in a random way. Then, you can upload the memories, and re-do the test of translation.

**Comment by LoekvanKooten** [comment]
Right after training I get this:

2019-03-07 18:46:07,777 DEBUG eu.modernmt.cluster.ClusterNode [main] Cluster node status changed: CREATED -> JOINING
2019-03-07 18:46:07,786 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2019-03-07 18:46:08,332 DEBUG eu.modernmt.cluster.ClusterNode [main] Cluster node status changed: JOINING -> JOINED
2019-03-07 18:46:08,333 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.396s
2019-03-07 18:46:08,333 DEBUG eu.modernmt.cluster.ClusterNode [main] Cluster node status changed: JOINED -> LOADING
2019-03-07 18:46:08,334 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2019-03-07 18:46:08,347 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2019-03-07 18:46:08,399 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 0s
2019-03-07 18:46:08,536 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on GPU 0 is starting
2019-03-07 18:46:11,593 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on GPU 0 failed to start
java.io.IOException: Failed to start neural decoder, received: null
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:107)
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:78)
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnGPU(PythonDecoderImpl.java:49)
	at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:55)
	at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:194)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Hardly any CPU or GPU memory is used. It just doesn't start. I train using tensorflow, then press Ctrl+C to interrput, then start the memory. This happens.

**Comment by LoekvanKooten** [comment]
I was able to reproduce the issue. The engine simply stops at Loading models in ModernMT 3.0. There is still tons of free CPU and GPU memory, so this is not being caused by memory issues. Then what is causing it?

**Comment by mtresearcher** [comment]
See the updates on #457 ... you should be able to start MMT on CPU. There seems to be an issue with using GPU memory.

**Comment by nicolabertoldi** [comment]
Hi @LoekvanKooten 

actually your problem seems like #457.

So please follow the same instructions I gave here
https://github.com/modernmt/MMT/issues/457#issuecomment-478896695

and please report your error

**Comment by davidecaroselli** [comment]
As reported in another thread, this issue seems to be solved. If not, please feel free to re-open it with newer infos.

Thanks!
