### ISSUE TITLE
Fast translation without live-adaptation

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#453]
I remember having read something about this: is there a command line option to translate a file without live-adaptation, so that the translation goes faster ?

**Comment by nicolabertoldi** [comment]
@EtienneAb3d 
If I well understood, you want to translate without adaptivity.
To do that you could run the following command
```mmt translate -s srclng -t trglng -e engine --batch < infile > outfile ```

In this way, the translation time is faster because fine tuning is not performed.

**Comment by EtienneAb3d** [comment]
Thanks !
It was what I was doing firstly. But, since I got a crash, logged as a problem with the DB, I thought the memory was involve. I'm not sure this crash was due to this processing. Perhaps because of an other one coming from a standard single translation call in the same time.

**Comment by EtienneAb3d** [comment]
Is there a way to define the beam_size to 1, in order to translate faster (with a loss in quality) ?

**Comment by nicolabertoldi** [comment]
ModernMT does not expose this parameter.

You can easily modify line 124 of this source file
```
src/decoder-neural/src/main/python/nmmt/transformer.py
```

setting `beam_size=1`

**Comment by davidecaroselli** [comment]
If you need any other info, please fell free to re-open the issue!
