### ISSUE TITLE
MMT 2.5 (phrase-based) re-training

### ISSUE THREAD

**Issue by MT-Group** [modernmt/modernmt#459]
Hello,

We are using 2.5 phrase-based customized systems and we would like to re-train one of them with an updated TMX. I've noticed that this is possible for neural:

"when you import a TMX file, it is added only to the translation memory manager and used for the adaptation. This way, we can use the most suitable the sentence pairs in each TM to adapt on the fly the neural (baseline-static) model, in order to improve the translation quality."

Does it work the same with phrase-based, or do I have to create the system from scratch?

Thank you!
Lucía

**Comment by davidecaroselli** [comment]
Hello Lucía,

while the internal implementation is completely different (phrase-based engine does not have a "memory", but an adaptive Language Model and Phrase Table), the feature is the same: even with phrase-based engine you can add new content (e.i. TMX) and the system will adapt and learn instantly, without the need for a re-train the whole engine.

This has always be the point of ModernMT, a real-time adaptive Machine Translation: it is true for Neural engine, it was the same for phrase-based :)
