### ISSUE TITLE
Memory updates not logged

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#460]
The returned result of a memory update:
Array
(
    [id] => 80000001-0000-0000-0000-00000000708a
    [memory] => 1
    [size] => 1
    [begin] => 28810
    [end] => 28810
    [dataChannel] => 1
    [progress] => 0
)

However, node.log makes no mention of the update or whatsoever. This is perfectly reproducable. Newest version.

**Comment by davidecaroselli** [comment]
Hi Loek,

this info is not logged on `node.log`, what you can see is the API call that returned HTTP code 200.
This is intended to prevent too verbose and not useful logging output.
