### ISSUE TITLE
Conflicting python 3.6 / 3.7

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#469]
I found why I got 2 conflicting python versions, as said in https://github.com/modernmt/modernmt/issues/449#issuecomment-489087213.
I put the solution here, in case someone get the same problem.
This is due to the installation of some packages using `conda`.
The solution is to reconfigure it with this command line:
`conda install python=3.6`

**Comment by davidecaroselli** [comment]
We will add a note to the Troubleshooting section of the INSTALL.md file, thanks for the suggestion!
