### ISSUE TITLE
f"sentence at index {idx} exceeds max_tokens limit!

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#470]
`./mmt create en nl data/engdut -e engdut -tensorboard-port 8066
Traceback (most recent call last):
  File "./mmt", line 75, in <module>
    main()
  File "./mmt", line 25, in main
    from cli import cleaning, datagen, train, create, server, translate, evaluate, memory
  File "/home/loek/mmt9/modernmt/cli/datagen.py", line 14, in <module>
    from mmt.textencoder import SubwordDictionary
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/loek/mmt9/modernmt/build/mmt-4.0.jar/mmt/__init__.py", line 4, in <module>
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/__init__.py", line 12, in <module>
    import fairseq.models
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/models/__init__.py", line 15, in <module>
    from .fairseq_model import (
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/models/fairseq_model.py", line 14, in <module>
    from fairseq.data import Dictionary
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/data/__init__.py", line 8, in <module>
    from .dictionary import Dictionary, TruncatedDictionary
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/data/dictionary.py", line 16, in <module>
    from fairseq.data import data_utils
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/data/data_utils.py", line 159
    assert sample_len <= max_tokens, f"sentence at index {idx} exceeds max_tokens limit!"
                                                                                        ^
SyntaxError: invalid syntax
`

@davidecaroselli 
@nicolabertoldi

**Comment by davidecaroselli** [comment]
`/home/loek/.local/lib/python3.5`

You're using python3.5, while ModernMT requires python3.6 (or newer).
You're system should be configured in order to have:
```bash
$ python3 --version
Python 3.6.7
```

**Comment by LoekvanKooten** [comment]
The whole python installation is a mess, but I think things are correct now.

This gives:

`./mmt create en nl data/engdut -e engdut -tensorboard-port 8066
Traceback (most recent call last):
  File "./mmt", line 75, in <module>
    main()
  File "./mmt", line 25, in main
    from cli import cleaning, datagen, train, create, server, translate, evaluate, memory
  File "/home/loek/mmt9/modernmt/cli/datagen.py", line 14, in <module>
    from mmt.textencoder import SubwordDictionary
  File "/home/loek/mmt9/modernmt/build/mmt-4.0.jar/mmt/__init__.py", line 4, in <module>
ModuleNotFoundError: No module named 'fairseq'
`
@davidecaroselli 
@nicolabertoldi

**Comment by davidecaroselli** [comment]
still problem in your python installation: your python3.6 has no `fairseq` module installed. To verify that:
```bash
$ python3
Python 3.6.7 (default, Oct 21 2018, 04:56:05) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fairseq
>>>
```

**Comment by LoekvanKooten** [comment]
It fails to install fairseq, it seems:

`python3 setup.py
Collecting regex (from -r /home/loek/mmt9/modernmt/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/11/d9/e37129676d508adf833fb3e3c3fbcb4e5a10183cf45b6c7edbaa57b4a1f2/regex-2019.04.14.tar.gz
Collecting sacrebleu==1.3.1 (from -r /home/loek/mmt9/modernmt/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/12/5b/7196b11bca204cb6ca9000b5dc910e809081f224c73ef28e9991080e4e51/sacrebleu-1.3.1.tar.gz
Collecting requests (from -r /home/loek/mmt9/modernmt/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting cachetools (from -r /home/loek/mmt9/modernmt/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Collecting torch (from -r /home/loek/mmt9/modernmt/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/69/60/f685fb2cfb3088736bafbc9bdbb455327bdc8906b606da9c9a81bae1c81e/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (676.9MB)
    100% |████████████████████████████████| 676.9MB 3.8kB/s 
Collecting torchvision (from -r /home/loek/mmt9/modernmt/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/fb/01/03fd7e503c16b3dc262483e5555ad40974ab5da8b9879e164b56c1f4ef6f/torchvision-0.2.2.post3-py2.py3-none-any.whl
Collecting fairseq==0.6.2 (from -r /home/loek/mmt9/modernmt/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/d7/b1/bb10d50b5fb0a030ddbeb049c8df66137f3a137e42d6d2474e73aa878a51/fairseq-0.6.2.tar.gz
Collecting typing (from sacrebleu==1.3.1->-r /home/loek/mmt9/modernmt/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r /home/loek/mmt9/modernmt/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->-r /home/loek/mmt9/modernmt/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->-r /home/loek/mmt9/modernmt/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r /home/loek/mmt9/modernmt/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting numpy (from torch->-r /home/loek/mmt9/modernmt/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 140kB/s 
Collecting pillow>=4.1.1 (from torchvision->-r /home/loek/mmt9/modernmt/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/d2/c2/f84b1e57416755e967236468dcfb0fad7fd911f707185efc4ba8834a1a94/Pillow-6.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 963kB/s 
Collecting six (from torchvision->-r /home/loek/mmt9/modernmt/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cffi (from fairseq==0.6.2->-r /home/loek/mmt9/modernmt/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/5f/bf/6aa1925384c23ffeb579e97a5569eb9abce41b6310b329352b8252cee1c3/cffi-1.12.3-cp36-cp36m-manylinux1_x86_64.whl (430kB)
    100% |████████████████████████████████| 440kB 2.1MB/s 
Collecting tqdm (from fairseq==0.6.2->-r /home/loek/mmt9/modernmt/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
Collecting pycparser (from cffi->fairseq==0.6.2->-r /home/loek/mmt9/modernmt/requirements.txt (line 7))
Building wheels for collected packages: regex, sacrebleu, fairseq
  Running setup.py bdist_wheel for regex ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c0h25lah/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp4jmt7r2rpip-wheel- --python-tag cp36:
  BASE_DIR is /tmp/pip-build-c0h25lah/regex
  /usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2019.04.14' to '2019.4.14'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/regex
  copying regex_3/regex/__init__.py -> build/lib.linux-x86_64-3.6/regex
  copying regex_3/regex/regex.py -> build/lib.linux-x86_64-3.6/regex
  copying regex_3/regex/_regex_core.py -> build/lib.linux-x86_64-3.6/regex
  creating build/lib.linux-x86_64-3.6/regex/test
  copying regex_3/regex/test/__init__.py -> build/lib.linux-x86_64-3.6/regex/test
  copying regex_3/regex/test/test_regex.py -> build/lib.linux-x86_64-3.6/regex/test
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/regex_3
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
  regex_3/_regex.c:48:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for regex
  Running setup.py clean for regex
  Running setup.py bdist_wheel for sacrebleu ... done
  Stored in directory: /home/loek/.cache/pip/wheels/56/c0/fb/1c7f9b3a71f64cdf86291cc645596f71746807bf2f72b3c1dd
  Running setup.py bdist_wheel for fairseq ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c0h25lah/fairseq/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp8vcurhu1pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/distributed_utils.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/progress_bar.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/bleu.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/search.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/trainer.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/meters.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/pdb.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/utils.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/sequence_scorer.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/legacy_distributed_data_parallel.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/__init__.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/binarizer.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/options.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/tokenizer.py -> build/lib.linux-x86_64-3.6/fairseq
  copying fairseq/sequence_generator.py -> build/lib.linux-x86_64-3.6/fairseq
  creating build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/interactive.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/generate.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/eval_lm.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/train.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/setup.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/score.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/__init__.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  copying fairseq_cli/preprocess.py -> build/lib.linux-x86_64-3.6/fairseq_cli
  creating build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/adam.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/fairseq_optimizer.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/adafactor.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/fp16_optimizer.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/sgd.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/adagrad.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/nag.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  copying fairseq/optim/adadelta.py -> build/lib.linux-x86_64-3.6/fairseq/optim
  creating build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/transformer.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/lstm.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/lightconv.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/fairseq_incremental_decoder.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/distributed_fairseq_model.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/fairseq_encoder.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/fairseq_model.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/composite_encoder.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/fconv.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/fairseq_decoder.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/fconv_self_att.py -> build/lib.linux-x86_64-3.6/fairseq/models
  copying fairseq/models/multilingual_transformer.py -> build/lib.linux-x86_64-3.6/fairseq/models
  creating build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/layer_norm.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/multihead_attention.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/adaptive_input.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/linearized_convolution.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/conv_tbc.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/lightweight_convolution.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/logsumexp_moe.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/beamable_mm.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/learned_positional_embedding.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/character_token_embedder.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/mean_pool_gating_network.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/sinusoidal_positional_embedding.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/adaptive_softmax.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/unfold1d.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/highway.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/dynamic_convolution.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/scalar_bias.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/grad_multiply.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  copying fairseq/modules/downsampled_multihead_attention.py -> build/lib.linux-x86_64-3.6/fairseq/modules
  creating build/lib.linux-x86_64-3.6/fairseq/tasks
  copying fairseq/tasks/translation.py -> build/lib.linux-x86_64-3.6/fairseq/tasks
  copying fairseq/tasks/language_modeling.py -> build/lib.linux-x86_64-3.6/fairseq/tasks
  copying fairseq/tasks/translation_moe.py -> build/lib.linux-x86_64-3.6/fairseq/tasks
  copying fairseq/tasks/multilingual_translation.py -> build/lib.linux-x86_64-3.6/fairseq/tasks
  copying fairseq/tasks/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/tasks
  copying fairseq/tasks/fairseq_task.py -> build/lib.linux-x86_64-3.6/fairseq/tasks
  creating build/lib.linux-x86_64-3.6/fairseq/criterions
  copying fairseq/criterions/composite_loss.py -> build/lib.linux-x86_64-3.6/fairseq/criterions
  copying fairseq/criterions/adaptive_loss.py -> build/lib.linux-x86_64-3.6/fairseq/criterions
  copying fairseq/criterions/cross_entropy.py -> build/lib.linux-x86_64-3.6/fairseq/criterions
  copying fairseq/criterions/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/criterions
  copying fairseq/criterions/label_smoothed_cross_entropy.py -> build/lib.linux-x86_64-3.6/fairseq/criterions
  copying fairseq/criterions/fairseq_criterion.py -> build/lib.linux-x86_64-3.6/fairseq/criterions
  creating build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/dictionary.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/language_pair_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/token_block_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/noising.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/iterators.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/data_utils.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/monolingual_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/round_robin_zip_datasets.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/backtranslation_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/fairseq_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/transform_eos_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/lm_context_window_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/concat_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/data
  copying fairseq/data/indexed_dataset.py -> build/lib.linux-x86_64-3.6/fairseq/data
  creating build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/inverse_square_root_schedule.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/triangular_lr_scheduler.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/reduce_lr_on_plateau.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/fairseq_lr_scheduler.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/fixed_schedule.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  copying fairseq/optim/lr_scheduler/cosine_lr_scheduler.py -> build/lib.linux-x86_64-3.6/fairseq/optim/lr_scheduler
  running build_ext
  building 'fairseq.libbleu' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/fairseq
  creating build/temp.linux-x86_64-3.6/fairseq/clib
  creating build/temp.linux-x86_64-3.6/fairseq/clib/libbleu
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c fairseq/clib/libbleu/libbleu.cpp -o build/temp.linux-x86_64-3.6/fairseq/clib/libbleu/libbleu.o -std=c++11
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c fairseq/clib/libbleu/module.cpp -o build/temp.linux-x86_64-3.6/fairseq/clib/libbleu/module.o -std=c++11
  fairseq/clib/libbleu/module.cpp:9:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fairseq
  Running setup.py clean for fairseq
Successfully built sacrebleu
Failed to build regex fairseq
Installing collected packages: regex, typing, sacrebleu, chardet, idna, urllib3, certifi, requests, cachetools, numpy, torch, pillow, six, torchvision, pycparser, cffi, tqdm, fairseq
  Running setup.py install for regex ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c0h25lah/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kcehctgx-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    BASE_DIR is /tmp/pip-build-c0h25lah/regex
    /usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2019.04.14' to '2019.4.14'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/regex
    copying regex_3/regex/__init__.py -> build/lib.linux-x86_64-3.6/regex
    copying regex_3/regex/regex.py -> build/lib.linux-x86_64-3.6/regex
    copying regex_3/regex/_regex_core.py -> build/lib.linux-x86_64-3.6/regex
    creating build/lib.linux-x86_64-3.6/regex/test
    copying regex_3/regex/test/__init__.py -> build/lib.linux-x86_64-3.6/regex/test
    copying regex_3/regex/test/test_regex.py -> build/lib.linux-x86_64-3.6/regex/test
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/regex_3
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
    regex_3/_regex.c:48:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c0h25lah/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kcehctgx-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-c0h25lah/regex/
You are using pip version 8.1.1, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    main()
  File "setup.py", line 236, in main
    pip_install()
  File "setup.py", line 219, in pip_install
    osutils.shell_exec(['pip3', 'install', '-r', requirements_txt], stderr=sys.stderr, stdout=sys.stdout)
  File "/home/loek/mmt9/modernmt/cli/utils/osutils.py", line 60, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.utils.osutils.ShellError: Command 'pip3 install -r /home/loek/mmt9/modernmt/requirements.txt' failed with exit code 1
`

**Comment by davidecaroselli** [comment]
Not sure which version of Ubuntu you have, but you're missing the package `build-essential`, that should be pre-installed. Just run:
```bash
sudo apt install build-essential
```

**Comment by LoekvanKooten** [comment]
That gives:

`sudo apt install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.`

@davidecaroselli 
@nicolabertoldi

**Comment by davidecaroselli** [comment]
Ok, so it must be python-dev that is missing:
```bash
sudo apt install python3-dev python3-setuptools python3-wheel
```

**Comment by LoekvanKooten** [comment]
That gives:

`sudo apt install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.
`

@davidecaroselli 
@nicolabertoldi

**Comment by LoekvanKooten** [comment]
Amended above.

**Comment by davidecaroselli** [comment]
@LoekvanKooten I believe you have a pretty bad python installation, this is very strange error. It is not even related directly to ModernMT, but with python's pip installation.

What version of Ubuntu are you using?

**Comment by LoekvanKooten** [comment]
@davidecaroselli  It's Ubuntu 16.04 LTS

**Comment by LoekvanKooten** [comment]
3.6 seems to be a mess. I installed Python 3.7 from source. 

That gave
`The directory '/home/loek/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/loek/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
`
python3 setup.py

would still fail, but

sudo python3 setup.py

did the trick. 

create is now running.

How to get rid of the messy 3.6 and the cache issue?

@davidecaroselli

**Comment by davidecaroselli** [comment]
This problem arises when you use `sudo pip3 install ...` instead of `pip3 install`. I don't know how to solve this problem, but I think you can find more info if you google it.
