### ISSUE TITLE
V4: ./mmt evaluate gives “Unexpected ERROR: 'builtin_function_or_method' object has no attribute 'uniform'“

### ISSUE THREAD

**Issue by mindaugasDEV** [modernmt/modernmt#472]
Hi,

Thanks, V4 works fine:
- new engine was trained successfully
- tensorboard was launched successfully

When I used Evaluate command, MMT4 was not calculating any score as it was complaining about context vector and was giving some error message (did not saved it), therefore I have just compiled the files to use the [commit](https://github.com/modernmt/modernmt/commit/0d1b2189e1f933fb4f7c9752bae6d6f64a712d7b). Voila, no more complains and MMT4 calculated the score!

However, now MMT4 calculate BLEU score fine, but Google Translate does NOT calculate the score and does complain in following way:

```
Translation Speed:
  ModernMT            : 0.11s per sentence
  Google Translate    : Unexpected ERROR: 'builtin_function_or_method' object has no attribute 'uniform'
```

Thank you for looking into it.

**Comment by davidecaroselli** [comment]
Hi @mindaugasDEV 

thanks for the report, can you please check that the last `versions/v4.0` commit has solved the problem?

Thanks!

**Comment by mindaugasDEV** [comment]
Issue solved, thanks a million! :)
