### ISSUE TITLE
Failed to start node (MMT 4)

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#475]
@davidecaroselli 
Did everything you said: brand-new install on Ubuntu 18.04. All looks fine. Model partially trained (interrupted with Ctrl+C). Build succesful.

`./mmt start -e japdut
Starting engine "japdut"...FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/loek/modernmt/runtime/japdut/logs/node.log
`

There is no node.log.

**Comment by davidecaroselli** [comment]
Ok let's see, from within `/home/loek/modernmt` try run:
```bash
java -server -Xms1024m -Xmx1024m -XX:ErrorFile=/home/loek/modernmt/runtime/japdut/logs/hs_err_pid%p.log -XX:+PrintGCDateStamps -verbose:gc -XX:+PrintGCDetails -Xloggc:/home/loek/modernmt/runtime/japdut/logs/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/loek/modernmt/runtime/japdut/logs -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:+CMSClassUnloadingEnabled -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -cp /home/loek/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/modernmt -Djava.library.path=/home/loek/modernmt/build/lib eu.modernmt.cli.ClusterNodeMain -e japdut --status-file /home/loek/modernmt/runtime/japdut/node.properties --log-file /home/loek/modernmt/runtime/japdut/logs/node.log
```

**Comment by LoekvanKooten** [comment]
java -server -Xms1024m -Xmx1024m -XX:ErrorFile=/home/loek/modernmt/runtime/japdut/logs/hs_err_pid%p.log -XX:+PrintGCDateStamps -verbose:gc -XX:+PrintGCDetails -Xloggc:/home/loek/modernmt/runtime/japdut/logs/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/loek/modernmt/runtime/japdut/logs -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:+CMSClassUnloadingEnabled -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -cp /home/loek/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/modernmt -Djava.library.path=/home/loek/modernmt/build/lib eu.modernmt.cli.ClusterNodeMain -e japdut --status-file /home/loek/modernmt/runtime/japdut/node.properties --log-file /home/loek/modernmt/runtime/japdut/logs/node.log
2019-05-07 14:29:13,696 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2019-05-07 14:29:13,699 main ERROR File not found in file system or classpath: /tmp/mmt_log4j21332841400598890648xml
2019-05-07 14:29:13,699 main ERROR Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'

**Comment by davidecaroselli** [comment]
You have an issue with your temp folder,  does it exist and can be accessed by the same user you're running ModernMT with?

**Comment by LoekvanKooten** [comment]
This is brand-new install of Ubuntu 18.04. Where should I find a temp folder or create it?

There's only one user on this system, who has access to everything.

**Comment by LoekvanKooten** [comment]
When I run said command, I see files being added to tmp if that's what you mean.

**Comment by davidecaroselli** [comment]
The problem is: running java directly works, while doing that by python doesn't.

Replace this line in your installation: https://github.com/modernmt/modernmt/blob/versions/v4.0/cli/utils/daemon.py#L21
with:
```python
dev_null = open('/tmp/loek-debug.log', 'w', encoding='utf-8')
```

and also add this line here: https://github.com/modernmt/modernmt/blob/versions/v4.0/cli/mmt/engine.py#L382
```python
        print(' '.join(command))
```

Now start the engine:
```bash
./mmt start -e japdut
```

and look at the output (where you should see the java command) and the temporary file `/tmp/loek-debug.log` where you should be able to see the stdout and stderr of the fava process.

**Comment by LoekvanKooten** [comment]
I gave up on MMT4 due to bad results with fairseq and reverted back to Ubuntu 16.04 with tensorflow.
