### ISSUE TITLE
cli.libs.osutils.ShellError (MMT 3)

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#476]
Meanwhile I'm frantically trying to get the previous version of MMT running again on Ubuntu 18.04:

`./mmt create en nl data/engdut -e engdut
An engine named "engdut" already exists, are you sure you want to overwrite it? [y/N] y

=========== TRAINING STARTED ===========

ENGINE:  engdut
CORPORA: 146 corpora
LANGS:   en > nl

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 1m 5s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 45s)
INFO: (3 of 6) Aligner training...                                     DONE (in 2m 56s)
INFO: (4 of 6) Preparing data...                                      
ERROR Unexpected exception: None

Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 145, in main_create
    builder.build()
  File "/home/loek/mmt8/cli/mmt/engine.py", line 632, in build
    self._build(resume=False)
  File "/home/loek/mmt8/cli/mmt/engine.py", line 704, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/loek/mmt8/cli/mmt/engine.py", line 498, in __call__
    self._f(*args, **kwargs)
  File "/home/loek/mmt8/cli/mmt/engine.py", line 836, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols, fromModel=self._fromModel)
  File "/home/loek/mmt8/cli/mmt/engine.py", line 167, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/home/loek/mmt8/cli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command 't2t-datagen --t2t_usr_dir /home/loek/mmt8/build/lib/t2t --data_dir=/home/loek/mmt8/runtime/engdut/tmp/training/neural_train_data/data --tmp_dir=/home/loek/mmt8/runtime/engdut/tmp/training/neural_train_data/tmp --problem=translate_mmt' failed with exit code 1
`

**Comment by davidecaroselli** [comment]
If you followed INSTALL.md of v4, the same setup **won't work** for MMT v3 too.

**Comment by LoekvanKooten** [comment]
@davidecaroselli Is there any way to get MMT3 running on Ubuntu 18.04? As there's no CUDA <= 9.0 for Ubuntu 18.04 for example. I keep getting the above error.

**Comment by LoekvanKooten** [comment]
Gave up on MMT4 due to bad results with fairseq and reverted back to Ubuntu 16.04 with MMT3.
