### ISSUE TITLE
Started engine does nothing (MMT 3)

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#477]
Copied engine from previous Ubuntu install:

./mmt start -e engdut
Starting MMT engine 'engdut'... OK
Loading models... OK

The MMT engine 'engdut' is ready.

You can try the API with:
	curl "http://localhost:8045/translate?q=world&source=en&target=it&context=computer" | python -mjson.tool

loek@Doraemon:~/mmt8$ ./mmt translate -e engdut "hello world"

ERROR Illegal State: MMT engine 'engdut' is not running.
Start it with "./mmt start"
You can check the status of your engines with "./mmt status"

**Comment by davidecaroselli** [comment]
I have no idea of what you're referring to anymore. Please open one "question" issue at time, if you try to do everything at the same time, I cannot help you. Try to solve one problem at time.

**Comment by LoekvanKooten** [comment]
This is MMT 3 in a different directory, with engines from a previous back-up that worked up to this morning.

**Comment by LoekvanKooten** [comment]
This seems to be caused by multiple installations of numpy, when following the standard installation procedure.

pip uninstall numpy (repeat until nothing is left)
pip install numpy

solves this.
