### ISSUE TITLE
Issue while training engine (please find the log attached)

### ISSUE THREAD

**Issue by kluda** [modernmt/modernmt#481]
./mmt create en it examples/data/train --train-steps 6000

=========== TRAINING STARTED ===========

ENGINE:  default
CORPORA: 3 corpora
LANGS:   en > it

WARNING: The RAM of GPU 0 is only 4G. More than 8G of RAM recommended for each GPU.

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 2s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 3s)
INFO: (3 of 6) Aligner training...                                     DONE (in 3s)
INFO: (4 of 6) Preparing data...                                      
ERROR Unexpected exception: None

Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 145, in main_create
    builder.build()
  File "/home/khalid/Downloads/modernmt-master/ModernMT/cli/mmt/engine.py", line 632, in build
    self._build(resume=False)
  File "/home/khalid/Downloads/modernmt-master/ModernMT/cli/mmt/engine.py", line 704, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/khalid/Downloads/modernmt-master/ModernMT/cli/mmt/engine.py", line 498, in __call__
    self._f(*args, **kwargs)
  File "/home/khalid/Downloads/modernmt-master/ModernMT/cli/mmt/engine.py", line 836, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols, fromModel=self._fromModel)
  File "/home/khalid/Downloads/modernmt-master/ModernMT/cli/mmt/engine.py", line 167, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/home/khalid/Downloads/modernmt-master/ModernMT/cli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command 't2t-datagen --t2t_usr_dir /home/khalid/Downloads/modernmt-master/ModernMT/build/lib/t2t --data_dir=/home/khalid/Downloads/modernmt-master/ModernMT/runtime/default/tmp/training/neural_train_data/data --tmp_dir=/home/khalid/Downloads/modernmt-master/ModernMT/runtime/default/tmp/training/neural_train_data/tmp --problem=translate_mmt' failed with exit code 1

**Comment by EtienneAb3d** [comment]
Is this a fresh install ? Did you try to reboot after installation ? Possibly, some paths are not well defined without a reboot. 
`t2t-datagen` should be in `/home/khalid/.local/bin`
With the command `echo $PATH` you should find this folder in the list.

**Comment by davidecaroselli** [comment]
Hello @kluda 

can you please attach here the log file here:
```
/home/khalid/Downloads/modernmt-master/ModernMT/runtime/default/logs/training.log
```

**Comment by kluda** [comment]
Hi @davidecaroselli please find the log file attached

[training.log](https://github.com/modernmt/modernmt/files/3165890/training.log)

**Comment by davidecaroselli** [comment]
You have the same error of #479 : "Something is wrong with the numpy installation."
In order to solve the problem:

1. you need to uninstall numpy with `pip uninstall numpy` until the error "Cannot uninstall requirement numpy, not installed" is shown, indicating you have no more numpy versions installed.
2. finally install numpy as reported in the INSTALL.md with `pip install numpy==1.14.5`

**Comment by davidecaroselli** [comment]
I have just updated INSTALL.md in order to remove that numpy install that was creating this problem.

@kluda please notice the warning you see at the beginning of the training: "WARNING: The RAM of GPU 0 is only 4G. More than 8G of RAM recommended for each GPU."

With 4G of GPU RAM it is very likely that you won't be able to train a proper model

**Comment by kluda** [comment]
@davidecaroselli now I am getting the below output:

./mmt create en it examples/data/train --train-steps 6000
  File "./mmt", line 44
    print 'ERROR: Wrong version of Java, required Java 8'
                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('ERROR: Wrong version of Java, required Java 8')?

**Comment by davidecaroselli** [comment]
1. you're using python3 instead of python2
2. "Wrong version of Java, required Java 8'" seems quite self-explanatory

**Comment by kluda** [comment]
Thanks @davidecaroselli I managed to overcome this step but now I am facing this issue:

When training the engine, it freezes at step 5 as show in the attached screenshot. It has been frozen for 20 hours and still counting up.

![Screenshot from 2019-05-14 02-09-06](https://user-images.githubusercontent.com/3491188/57660074-84f72880-75ed-11e9-9a51-8329a451e140.png)
[training.log](https://github.com/modernmt/modernmt/files/3175139/training.log)

**Comment by davidecaroselli** [comment]
Hi @kluda 

as far as I can tell the process seems ok. The training process is still on going (as you can see from the train.log file). I think it is incredibly slow due the poor GPU you're using - you can see ModernMT complaining too on the few GPU RAM available.

It's up to you when you want to stop the training, just hit Ctrl+C (or `kill -2 <pid>` if running in background) but please consider that an acceptable number of updates are something like 100.000, you're now at 3000.

**Comment by LoekvanKooten** [comment]
@davidecaroselli I now installed 64 GB of RAM in my machine and can run dozens of engines at once now. It certainly helps :D

**Comment by davidecaroselli** [comment]
Nope. Don't mix the two things.

**GPU RAM** is the amount of RAM mounted on the GPU, it depends on the GPU model (i.e. GTX1080 has 8Gb, GTX1080Ti has 11G).

**System RAM (or RAM)** is the amount of RAM installed on your PC, and that's can be changed by installing more blocks.

GPU RAM cannot be upgraded, you have to change Graphic Card model.

**Comment by LoekvanKooten** [comment]
@davidecaroselli  

I've got 11 GB GPU RAM and 64 GB System RAM.

The System RAM was needed, as I couldn't run more than 3 engines simultaneously with 16 GB System RAM.

**Comment by davidecaroselli** [comment]
Hi @kluda 

a quick update: with the new ModernMT v4.0 we have implemented a new automatic stopping policy, so you won't need to manually check and stop the training anymore!

In any case, you will have much more info on the training in its log file: `runtime/<engine-name>/logs/training.log`
