### ISSUE TITLE
MMT 3.3.1 successfully installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#482]
Following the latest discussion, I would like to inform you that I successfully installed MMT 3.3.1 on Ubuntu 18.04. As I experienced some system freezes in intermediate installation configurations, I will wait several hours of running before compiling an installation procedure to share here.
The key elements are:
- Ubuntu 18.04 delivers Python 2.7 by default (it was said to be Python 3)
- Cuda9 can be installed after having installed Cuda10
- it's very important do properly specify all Python package versions to avoid conflicting older with newer ones

As MMT2 and MMT3 offer very complementary qualities, with statistical / RNN / Transformer architectures, I strongly invite MMT team to ensure that they are always both available and installable on new machine configurations.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

I sincerely advise to use Docker for production environments.
In my opinion installing ModernMT from source (or binary) should be used only for developers or "evaluation" purposes, and only if you don't care to "mess" a bit with installations, libraries etc.
Docker containers aim to resolve this exact problem: you can run your container no matter what your current system setup is. You can run the same ModernMT container in a Ubuntu 16.04, 18.04 or not even an Ubuntu distro: it is indeed very powerful and give you the maximum stability and predictability at runtime.

The only constraint with GPU-enable applications like ModernMT is that the nvidia drivers version must be the same from the host machine and the container, but beside that, no other libraries are required.

**Comment by EtienneAb3d** [comment]
Having the same NVidia driver is already possibly a problem. 
But, more than this, I've tuned a little bit some part of code, like the context vector rescoring (as explained in a past post: addition replaced by a product).

**Comment by EtienneAb3d** [comment]
All seems ok. These instructions are supposed to be neither minimal, nor exhaustive. Here is just how I succeeded in installing MMT 3.3.1 from sources.

```
Install XUbuntu 18.04 up to date on your machine.
Remark: XUbuntu 18.04 uses Python2.7 by default.

Install latest NVidia driver:
	boot in recovery mode with a root command line
	be sure having gcc and make installed. May be installed with the root shell if net access activated.

From official NVidia web site, follow installation instructions for the latest version available:
Install cuda 10.1:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal
Install cuDNN for cuda 10.1:
https://developer.nvidia.com/rdp/cudnn-download

Download and install cuda 9.0 and patches, except the last install command:
https://developer.nvidia.com/cuda-90-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1704&target_type=deblocal
In place of:
	sudo apt-get install cuda
Do the following:
	open synaptic
	search for "cuda 9-0"
	click to install it

Do the same with cuda 9.2:
https://developer.nvidia.com/cuda-92-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1710&target_type=deblocal

Install jkd8:
	sudo apt install openjdk-8-jdk
Force java8 as default:
	sudo update-alternatives --config java
Install cmake liboost-all-dev:
	 sudo apt install cmake liboost-all-dev

Install tensorflow like explained here, using precise version specifications:
https://www.tensorflow.org/install/pip?lang=python2
	cd ~/
	virtualenv --system-site-packages -p python2.7 ./venvMMT331
	source ./venvMMT331/bin/activate
	pip install -U requests
	pip install numpy==1.14.5
	pip install tensorflow-gpu==1.8.0
	pip install tensor2tensor==1.6.3
	pip install tensorboard==1.8.0
	pip install --upgrade oauth2client

Reboot needed in order to make all PATH properly set.

Install MMT331, like explained on the MMT GIT repository (venvMMT331 needs to be activated):
	cd vendor
	python download_dependencies.py
	cd ..

	cd src
	mvn clean install
	cd ..


```

**Comment by davidecaroselli** [comment]
Thanks for sharing this!
