### ISSUE TITLE
MMT331 no more responding

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#484]
I'm back to a problem I already have seen with MMT4, and never seen before with MMT2 or MMT323. As I'm on a new machine, I don't really know if this is due to this machine, or to MMT versions. 

Here is the procedure that gives a deterministic result:
1) create a dozen of memories.
2) fill them with a few sentence pairs, and translate, with or without context, thus with or without memory access. All is working properly, meaning the installation is well operational.
3) if you wait few seconds, or event few minutes, all is still working properly.
4) wait a dozen of minutes without activity.
5) MMT331 is then no more responding, at any kind of request, without any message visible on logs (MMT / Cassandra / Kafka)

Incredible !?

**Comment by EtienneAb3d** [comment]
I succeeded in making working my old MMT323 on this machine, using a copy of dependencies downloaded at the date it was released. 
MMT323 seems perfectly stable ! I do not encounter the blocking problem like with MMT331 or MMT4.
I think there is certainly a stability problem with latest releases of MMT331 and MMT4, at least on my machine configuration.

**Comment by LoekvanKooten** [comment]
Currently MMT4 is exit for me anyway. The results of fairseq are far, far worse than those of Tensorflow. Unusable in my case.

**Comment by EtienneAb3d** [comment]
I will give an other chance to MMT4 later. But, now, after more than one full week of hard work to succeed in having something properly running on this new machine, I need to go forward with what is working, thus MMT323.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

I have (finally) observed the same issue in one of our dev servers. Just like you said - it is not even related to memories, it's just ModernMT stop responding to HTTP requests.

Because the problem is totally independent from ModernMT actual work, I looked at Jetty, that is the Web-library we use for HTTP requests serving.

The bug arises with a ModernMT using Jetty version `9.4.17.v20190418` (you can check the version here: https://github.com/modernmt/modernmt/blob/master/src/core/pom.xml#L62 ). So first question: could you please check if both versions that are giving you problems are using this Jetty version?

Now, on next Jetty release notes, available [here](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.18.v20190429) we can read:
> + 3550 Server becomes unresponsive after sitting idle from a load spike

This sounds too much familiar. So I suspect the problem was due a bug in Jetty.

In latest commits of both `master` and `versions/v4.0` branches I have updated the Jetty version to 9.4.18. Please let me know if this solves the issue.

**Comment by EtienneAb3d** [comment]
It seems I have exactly the same thing on all installed version of MMT, working or blocking.

Possibly I do not look at the right place.

In the working MMT323:
```
./vendor/kafka-1.1.0/libs/jetty-servlet-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-security-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-servlets-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-client-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-http-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-continuation-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-util-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-io-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-server-9.2.24.v20180105.jar
```

In the blocking MMT331:
```
./vendor/kafka-1.1.0/libs/jetty-servlet-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-security-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-servlets-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-client-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-http-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-continuation-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-util-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-io-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-server-9.2.24.v20180105.jar
```
I can't check back the really experimented MMT4, because the machine was fully re-installed since that. But, on a not-tested previous installation on an other machine, I have the same:
```
./vendor/kafka-1.1.0/libs/jetty-servlets-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-client-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-servlet-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-util-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-http-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-security-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-continuation-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-server-9.2.24.v20180105.jar
./vendor/kafka-1.1.0/libs/jetty-io-9.2.24.v20180105.jar
```
I have to go back to my old MMT21 to find something else:
```
./vendor/kafka-0.10.2.1/libs/jetty-security-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-util-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-server-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-http-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-servlets-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-continuation-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-io-9.2.15.v20160210.jar
./vendor/kafka-0.10.2.1/libs/jetty-servlet-9.2.15.v20160210.jar
```

**Comment by davidecaroselli** [comment]
no, that's not the right spot. The file to look into is `src/core/pom.xml` at line 59 and 64, you should see something like this:
```xml
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>XXXXX</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>XXXXX</version>
        </dependency>
```
```

**Comment by EtienneAb3d** [comment]
Working MMT323:
```
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>9.3.6.v20151106</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>9.3.6.v20151106</version>
        </dependency>
```

Blocking MMT331:
```
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>9.4.17.v20190418</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>9.4.17.v20190418</version>
        </dependency>
```
 
Not-tested, but certainly the same as the blocking MMT4:
```
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>9.4.17.v20190418</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>9.4.17.v20190418</version>
        </dependency>
```

**Comment by davidecaroselli** [comment]
That seems to confirm the problem. **The problem arises with Jetty 9.4.17**.
I'm running some stress tests right now, I'll let you know.

**Comment by EtienneAb3d** [comment]
In this case, you should not be too stressful: the problem is coming after a no-activity time.
;-)

**Comment by davidecaroselli** [comment]
Yeah, my stress test is "do a lot of stuff -> wait 30m -> test"

**Comment by davidecaroselli** [comment]
@EtienneAb3d the fix seems to work!
Finally solved this: the problem was a bug in the Jetty library.

Thanks for your support!
