### ISSUE TITLE
Error in installation instructions

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#488]
7.5.1 can no longer be downloaded. Trying 7.6.0 for CUDA 10 now.

Next install the NVIDIA cuDNN library from: NVIDIA cuDNN Download. Select the option "Download cuDNN v7.5.1 (April 22, 2019), for CUDA 10.0" and then "cuDNN Runtime Library for Ubuntu18.04 (Deb)". Finally simply run this command on the downloaded package:

sudo dpkg -i libcudnn7_7.5.1.10-1+cuda10.0_amd64.deb

**Comment by nicolabertoldi** [comment]
Installation documentation fixed.
