### ISSUE TITLE
No such file or directory: 'fairseq-preprocess': 'fairseq-preprocess'

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#489]
After a totally clean install from Source on a clean Ubuntu 18.04 without any errors or whatsoever, right after step 4/4 Generating binary data:

ERROR Unexpected exception: [Errno 2] No such file or directory: 'fairseq-preprocess': 'fairseq-preprocess'

which fairseq-preprocess (or which fairseq for that matter) gives nothing

pip3 install fairseq
Collecting fairseq
Collecting tqdm (from fairseq)
  Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
Collecting sacrebleu (from fairseq)
  Downloading https://files.pythonhosted.org/packages/16/54/165b8d208788b99546032b0053b7c0fa61fa7bf2b55237d78a895168c24e/sacrebleu-1.3.4.tar.gz
Collecting numpy (from fairseq)
  Using cached https://files.pythonhosted.org/packages/87/2d/e4656149cbadd3a8a0369fcd1a9c7d61cc7b87b3903b85389c70c989a696/numpy-1.16.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting cffi (from fairseq)
  Using cached https://files.pythonhosted.org/packages/5f/bf/6aa1925384c23ffeb579e97a5569eb9abce41b6310b329352b8252cee1c3/cffi-1.12.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting typing (from sacrebleu->fairseq)
  Using cached https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting pycparser (from cffi->fairseq)
Building wheels for collected packages: sacrebleu
  Running setup.py bdist_wheel for sacrebleu ... done
  Stored in directory: /home/loek/.cache/pip/wheels/5a/80/a8/e149303db81e58e7dbb29ee7943c43da9861872a5ea550256c
Successfully built sacrebleu
Installing collected packages: tqdm, typing, sacrebleu, numpy, pycparser, cffi, fairseq
Successfully installed cffi-1.12.3 fairseq-0.6.2 numpy-1.16.4 pycparser-2.19 sacrebleu-1.3.4 tqdm-4.32.1 typing-3.6.6

loek@DORAEMON:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
loek@DORAEMON:~$ python3 --version
Python 3.6.7
loek@DORAEMON:~$ pip3 show fairseq torch
Name: fairseq
Version: 0.6.2
Summary: Facebook AI Research Sequence-to-Sequence Toolkit
Home-page: https://github.com/pytorch/fairseq
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: tqdm, sacrebleu, numpy, cffi
---
Name: torch
Version: 1.0.1.post2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: 

@davidecaroselli @nicolabertoldi

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

what do you get if you run the command 
```fairseq-preprocess```

from a shell


where the same command is located? run the following 
```
which fairseq-preprocess
```

**Comment by LoekvanKooten** [comment]
/home/loek/.local/bin/fairseq-preprocess

@nicolabertoldi

**Comment by LoekvanKooten** [comment]
Hm, now it's doing something. Apparently I just needed to restart?
