### ISSUE TITLE
Tensorboard loses connection after a while

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#491]
If you create a new engine with the Tensorboard option, after a while (30 minutes or so?), Tensorboard will lose its connection and give a 404. Restarting Tensorboard manually from another terminal window solves this issue - in this case, the connection does not get lost. This is perfectly reproducable.

**Comment by cettolo** [comment]
I observed the same behavior...

**Comment by davidecaroselli** [comment]
Hi!

I have just pushed a fix in `master` branch, can you give it a try please?

**Comment by davidecaroselli** [comment]
Solved and published with ModernMT v4.1. Thanks all for the support!
