### ISSUE TITLE
Version 3 installation instructions?

### ISSUE THREAD

**Issue by gdaine** [modernmt/modernmt#494]
Is there an archived version of the installation instructions (from source) for mmt v3?
I upgraded to Ubuntu 18.04/mmt 4 but then I found that mmt 4 just doesn't run on my GPU - GTX 1060. It keeps skipping batches during training due to lack of memory.
Now I'm going to revert to 16.04 and reinstall version 3, which works fine on this hardware, but I need the detailed instructions.
Thanks for any pointers.

**Comment by nicolabertoldi** [comment]
@gdaine 

You can get the source code of version 3.3 (*v3.3) from here
https://github.com/modernmt/modernmt/tree/v3.3

All older versions are also available.
More in general, you can go to our github page
click on **branches**, select **Tags*, and then choose the version you like.



You have also the possibility to continue working with v4 by reducing the batch size to fit in the memory.
To do that modify the default parameter `max-tokens` through the command `mmt create`, running something like
```
mmt create en it DATA --max-tokens 2048
```
or any other value.

**Comment by EtienneAb3d** [comment]
MMT3 may be installed on Ubuntu 18.04: see #482

**Comment by gdaine** [comment]
Thanks. I didn't realise the documentation was included in the code.
I'll try v4 again with reduced batch size and see what happens.
Closing this issue.
