### ISSUE TITLE
MMTv4 multilingual engines

### ISSUE THREAD

**Issue by cettolo** [modernmt/modernmt#495]
Hi MMTers
it seems that instructions for building [multilingual engines](https://github.com/modernmt/modernmt/wiki/Multilingual-Engines) are no more valid for MMT version 4. I suggest to keep them just for versions 2.* and 3.*, and add specific instructions for v4, where useless sections are removed (e.g. "Merge the aligner models") and other sections are updated (e.g. "Configuration file" has to follow what is written [here](https://github.com/modernmt/modernmt/wiki/advanced-configurations#languages)).

**Comment by nicolabertoldi** [comment]
@cettolo 
thanks for reporting.
We will revise the documentation asap .

**Comment by arteq** [comment]
Hello, any estimate on when this 'asap' could be?
We are very happy after switching from v3 to v4 in terms of translation quality but the inability to create multilang engine is a big step back...

**Comment by davidecaroselli** [comment]
Hi @cettolo and @arteq 

thanks for your patience, we have just updated our wiki page for [multilingual engines](https://github.com/modernmt/modernmt/wiki/Multilingual-Engines).

Thanks for you support!
