### ISSUE TITLE
DecoderUnavailableException

### ISSUE THREAD

**Issue by jgrivolla** [modernmt/modernmt#497]
I frequently get `{"error":{"type":"DecoderUnavailableException","message":"No active nodes in the cluster"},"status":503}` when calling the translation REST service.

I'm using ModernMT v3.3.2 inside Docker, without GPU. It's always rather slow, which is expected on CPU, but additionally it frequently fails completely.

**Comment by nicolabertoldi** [comment]
@jgrivolla 
this message just says that the engine did not start properly, or that it died at some point.

In order to understand the reason for thar, we should give a look at the file "runtime/ENGINE/logs/node.log".

**Comment by davidecaroselli** [comment]
I'm closing this due inactivity, @jgrivolla please feel free to re-open the issue if you have new insights.
