### ISSUE TITLE
Hosting options

### ISSUE THREAD

**Issue by popstick** [modernmt/modernmt#498]
Sorry if this is the wrong place to ask. I’m wondering what would be the most cost effective way to host a rest server that would serve a few hundred users a day? Would a gpu machine be absolutely necessary?

**Comment by davidecaroselli** [comment]
Hi @popstick 

yes, a GPU machine is absolutely necessary. Even if you can run translations on CPUs in theory, practically speaking this is not a real option (from 10x to 100x time). I would suggest to start with a single GPU machine to start experimenting yourself the code. For an in-production machine I would rather advice a 4-8 GPUs machine to handle peaks.
