### ISSUE TITLE
Translation speed when using FP16

### ISSUE THREAD

**Issue by ecly** [modernmt/modernmt#507]
I am experimenting with FP16 for MMT, and have ran into some peculiar results.
I have seen @davidecaroselli boxing with FP16 in fairseq's issues, so thought we might be able to make it a joint effort.

I run my experiments using an RTX 2080ti, using the newest MMT with default provided example data.

I train a model using:
```bash
./mmt create -e bigfp16 en it examples/data/train/ \
  --train-steps 1000 \
  --save-interval 999 \
  --arch transformer_mmt_big \
  --fp16
```

Testing with fp16, memory-efficient-fp16, I get the following training times (from the log).
- fp16: 8m 34s
- memory-efficient-fp16: 9m 7s
- fp32: 21m 39s

To test the translation speed of each of these, I run:
```bash
./mmt start -e bigfp16 && \
  time head -100 examples/data/train/europarl.en | ./mmt translate -e bigfp16 --batch && \
  ./mmt stop -e bigfp16
```
This results in the following wall clock times:
- fp16: 40s
- memory-efficient-fp16: 43s
- fp32: 33s

which basically contrasts my expectations. We would not expect a huge speedup, as the `./mmt translate` basically does no low-level batching (from what I can understand), but I would certainly not expect a slowdown?

Additionally, I am suprised that each of the checkpoints stored for the 3 different models, all are of the same size (namely 2.2GB). If I use `fairseq-cli` directly, checkpoints will be smaller when using `--fp16` or `--memory-efficient-fp16`. Hence I wonder if I might be doing something wrong as I am relatively new to MMT, or whether the MMT setup is not entirely set up for using `--fp16` yet.

**Comment by nicolabertoldi** [comment]
@ecly 

your figures confirms our experiments.

fp16 is faster than fp32 during training but slower during inference.
The reason is that in order to use fp16 a few operations to cast the tensors from/to fp32 are performed, for every batch.
The cost of the cast operations is negligible during training because of the use of large batches, while it is consistent in inference because the batch consists of one single sentence.

Regarding the size of the checkpoints, actually we store the fp32 version of the tensor even if we use fp16 during training. Maybe, we can revise this choice in the future.

**Comment by ecly** [comment]
@nicolabertoldi 

Thanks for the snappy response.

A few comments regarding this. Seeing as we get this great speed-up during training, it might make sense to simply use the fp32 model rather the fp16 when we load the engine, since we could then train efficiently using fp16, but remove the fp16 overhead during inference. 

A follow-up question. I know that the entire context-vectoring infrastructure currently in-place is incompatible with low-level batching, as we basically cater the engine to each specific input, but are there any plans to implement low-level batching during inference? This would also allow some of the fp16 improvements to flourish even during inference for batched input.

**Comment by nicolabertoldi** [comment]
@ecly 

thanks for your hints.
We are already considering to have some batching in the inference phase, but we have not yet decided whether to implement or not any batching solution.

Please stay tuned to know about possible enhancements in this direction.

**Comment by nicolabertoldi** [comment]
@ecly 

ModernMT is an adaptive system: for each input sentence the system is fine-tuned according to the "context" of the input itself.

The fine-tuning is achieved by a super-fast training phase of the network. During that, the cast operations occur.
In other words, the translation of a sentence is composed by a training phase (requiring the cast) and an inference phase.

**Comment by ecly** [comment]
You are right - for that use-case I see how this casting would then be necessary.

From my diving into the MMT code I would however expect the the above testcase to have no context, eg. no 'suggestions', as these are added through the REST API? Because of this I would expect an empty `suggestions` list in [decoder.py](https://github.com/modernmt/modernmt/blob/master/src/decoder-neural/src/main/python/mmt/decoder.py#L172), resulting in no tuning, and thereby no casting, effectively causing no slowdown despite the lack of batching?

**Comment by nicolabertoldi** [comment]
@ecly 

we will take into consideration whether implementing the possibility to discard the cast operation in case of not-adaptive translation.

**Comment by ecly** [comment]
@nicolabertoldi cheers - I would consider it a nice addition.

I also expect that the adaptive training will be quite difficult to run alongside low-level batching (at least I see no obvious way to do this), so it would be a nice thing to basically have the option disabling the adaptive part for a huge speed increase.

I think that would be my preferred way at least, and then just doing context specific engines, instead of on-the-fly context fine-tuning.

Lastly - for the time being. Do you think there is any current way that I can run my training with FP16, and then have everything running with FP32 for inference, so that I can avoid any casting during inference, but still get the big speed increases during training?

**Comment by nicolabertoldi** [comment]
@ecly

actually, the system should work with fp32 during translation, even if the training was performed with fp16.

But I have to double-check.
I will report in few days.

**Comment by ecly** [comment]
Cheers - having conducted a couple more experiments, with inference across FP16 trained model and FP32 trained, I was getting uncertain myself, as my results weren't always fully consistent. So would be nice to know!

**Comment by ecly** [comment]
Since this is stale, and the dangling question is not too important for me right now, I'll close this issue.
