### ISSUE TITLE
Using glossary terms

### ISSUE THREAD

**Issue by dagid4** [modernmt/modernmt#512]
Hello, I'm trying to preserve glossary terms in their original form. I have tried with memory:

`./mmt memory create test`
`1: test`

`./mmt memory add 1 "Shield" "Shield"`
`Contribution added to memory 1`

It works if the term matches the whole source:

`./mmt translate "Shield"`
`Stínění`

`./mmt translate "Shield" --context-vector 1:1.0`
`Shield`

But it doesn't work if the term is used in sentence:

`./mmt translate "The best Shield is from Nvidia."`
`Nejlepší stínění je od Nvidia.`

`./mmt translate "The best Shield is from Nvidia." --context-vector 1:1.0`
`Nejlepší stínění je od Nvidia.`

Is it possible to somehow force the engine not to translate the word "Shield"? It should be:

`Nejlepší Shield je od Nvidia.`

**Comment by EtienneAb3d** [comment]
What you can do is to tag the word in the input sentence, and hope the tag to be at the right place in the output to replace the translation words.
```
./mmt translate "The best <term1>Shield</term1> is from Nvidia."
Nejlepší <term1>stínění</term1> je od Nvidia.
```
Depending on the context, it may bring you with strange formulations, but this is the only way to do an exact term translation.

The other way is to massively add sentence pairs to the training data containing your terminology...

**Comment by dagid4** [comment]
I think the way with tags could work. Thank you very much.
