### ISSUE TITLE
Using `nbest` in MMT 4.2

### ISSUE THREAD

**Issue by ecly** [modernmt/modernmt#515]
Sorry if I was simply unable to find documentation for this, but is there any reason for the `nbest` option not being supported in MMT 4.2, considering the support on the `fairseq` side of things?
```bash
curl -s -X GET http://localhost:8045/translate \
     -d "source=de" \
     -d "target=en" \
     -d "q=Ich bin Emil" \
     -d "nbest=2" \
     | python -mjson.tool
{
    "status": 500,
    "error": {
        "type": "UnsupportedOperationException",
        "message": "Decoder 'NeuralDecoder' does not support N-best."
    }
}
```

**Comment by nicolabertoldi** [comment]
@ecly 

There is no theoretical limit.
It was just a business choice.

If you are interested in this feature, I would kindly ask you to create a new ticket highlighting the label "feature requests", and providing reasons why you think this is important.

**Comment by ecly** [comment]
Cheers @nicolabertoldi , I will create a ticket describing what I intended to use this for.
