### ISSUE TITLE
Is MMT development still going on or is it dead?

### ISSUE THREAD

**Issue by mzeidhassan** [modernmt/modernmt#526]
Hi @davidecaroselli and @nicolabertoldi ,

I hope you are doing OK and it's all well with you. 

I am not used to see no responses from you for a long time. I hope you are doing OK.

Thanks,
Mohamed

**Comment by ecly** [comment]
While issue response has certainly stagnated recently, if you look at the commit history/activity of the different public branches, you will see that development is indeed not dead.

**Comment by mzeidhassan** [comment]
Thanks @ecly! I hope the whole team is doing just fine. This is the first time I see such delay in responses.

**Comment by mzeidhassan** [comment]
Actually, it seems @davidecaroselli has just pushed 4.4 release 2 hours ago :-)
