### ISSUE TITLE
Kafka v4.4 compatibility

### ISSUE THREAD

**Issue by mzeidhassan** [modernmt/modernmt#528]
Hi @davidecaroselli ,

Thanks for the new release.

In your changlog, you wrote the following:

> v4.4 Kafka and memory models are not compatible with previous versions.

My question is:
If I upgrade my current version to 4.4, would I face any problems? Do I need to retrain my engine? Maybe not in terms of training, but what about my current added memories? Do I need to delete them and recreate new ones after upgrade?

Thanks,
Mohamed

**Comment by ecly** [comment]
@mzeidhassan I believe the release notes are fairly clear about this. 
You do not need to retrain the engine, but you should upgrade your Kafka and reimport all memories to have guarantees about compatibility.

**Comment by mzeidhassan** [comment]
Thanks @ecly for your kind follow-up. I am closing the issue.
