### ISSUE TITLE
Purpose of Kafka in Context Memory setup

### ISSUE THREAD

**Issue by ecly** [modernmt/modernmt#530]
In the process of setting up shared context memories across multiple concurrently running engines, I started questioning exactly what the purpose of Kafka is in the stack? I assume the actual data is stored in Cassandra/MySQL, so all I could think of was as a caching layer or maybe it is only useful as an external service when using ModernMT as a cluster?

In my usecase, I am trying to set up multiple multilingual engines (currently not using MMT cluster functionality), with no language combination overlap between the engines. If I simply want to share a MySQL database, eg. for persisting context memories between deployments etc., would it be fine to keep Kafka embedded, or is there any reason I should also externalize that?

**Comment by davidecaroselli** [comment]
Hi @ecly 

Kafka is used as a "binary log" for all the memory-related operations: import, single-add, single-update and delete.
The way ModernMT works is by enqueueing every single segment of a memory import into Kafka and then let every node in the cluster read from the binlog and store the data inside their models. In fact segments are not stored into MySQL/Cassandra database, but they are stored inside Kafka as a queue and inside the native models of the Translation Memory and Context Analyzer components.

This architecture allow you to join any number of nodes in the cluster and be sure that all of them are up-to-date with the latest import, even if it was complete days before a new node joins the cluster.

**Comment by ecly** [comment]
Thank you very much for the answer @davidecaroselli - that clarified a lot.
Appreciate it.
