### ISSUE TITLE
Resume still only works after --debug

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#532]
Unfortunately I have to confirm that even in the very newest version of ModernMT (4.5.3), --resume won't work if the --debug flag hasn't been used before. After completing a succesful training (for example after pressing Ctrl+C because the computer MUST be restarted for whatever reason), ModernMT deletes the entire training directory, and there's no way to get it back.

I just lost four hours of training this way.

Can't we just make it so that --resume always works? I don't think anyone cares about wasting a few bytes of disk space in forgotten directories. These can always be deleted manually later. Deleted training data however, never comes back.

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten 

I agree. I have just pushed a commit in the master branch which solves this issue by changing the default behavior. Now, by default, `mmt create` will keep temporary files unless explicitly told to remove them with `--delete` flag.
