### ISSUE TITLE
Traduzione molto lenta e caratteri tradotti in piu (in DashBoard)

### ISSUE THREAD

**Issue by Master-Antonio** [modernmt/modernmt#535]
Salve a tutti, sto usando il vostro MT per tradurre un videogioco, traduzione Fan Base, che si chiama Black Desert Online, per PC.
La localizzazione è circa 700 mila stringhe, circa 6 millioni di caratteri in tutto.
Sono riuscito a convertire in txt e poi in json, che poi ho splittato in 23 file di ognuno 30 stringhe
Fatta questa premessa, ho integrato nel convertitore che converte dal file originale ad un file leggibile (txt e json), il vostro MT, ho avviato la traduzione, è in 5-6 ore non ha tradotto nemmeno 1 file che sono circa 30 mila stringhe, ho fatto un -tail -f su Linux, e noto che la traduzione viene stoppata dopo un po per poi reiniziare, rimane in stallo, tipo fa prima 20 stringhe, poi si stoppa 40-50 secondi per poi reiniziare e ripetere lo stesso problema dopo poco tempo, avevo già fatto attenzione prima, perchè con Crowdin con gli MT integrati in circa  3-4 orette in tutto traducevo tutte e 23 i file.
Qua invece nemmeno 1 file in 6 ore, c'è qualcosa che non quadra, anche perchè andando nella Dashboard del sito noto un numero di caratteri usati che non rispecchiano per niente il dato reale, 6 millioni sono tutte e 23 i file, è impossibile quel numero solo per 1 file ...
Il mio convertitore con MT è in JAVA ed è Open Source, se volete aiutarmi e cercare di risolvere questo problema fastidioso, posso mandarvi il link della repository con il codice aggiornato.
Grazie mille.

**Comment by davidecaroselli** [comment]
Ciao Antonio,

chiudo questo issue semplicemente perché abbiamo avuto modo di continuare la discussione privatamente per email e, forse più importante, questo problema comunque sia è relativo al nostro servizio cloud e non al progetto Open-source di ModernMT che è questo repository.

Grazie mille per la comprensione!
