### ISSUE TITLE
"Expecting value: line 1 column 1 (char 0)" when starting engine

### ISSUE THREAD

**Issue by ecly** [modernmt/modernmt#538]
I apologize for the very vague issue title, but this is a somewhat sporadic issue, that I occasionally see in my training scripts, when trying to start a ModernMT engine right after the training of it has finished.

It happens during `./mmt start -e <engine-name>` and all that is printed to conosole is:
```
ERROR Unexpected exception: Expecting value: line 1 column 1 (char 0)
```

The 'node.log' file contains:
```
2020-05-24 18:10:22,356 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
        at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:92)
        at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
```
which wasn't all that helpful.
Any experience with this issue, where it might originate from, or what I can do to avoid it happening?

**Comment by EtienneAb3d** [comment]
Try to start with option `-v 3`, you will possibly get more infos in the LOG file.

**Comment by ecly** [comment]
Hey @EtienneAb3d, I have sadly never got an easily reproducible case of this, and it has only appeared in logs from time to time, for my training scripts, so I was very much hoping someone might have experience with this except error.

I may however try adding this option to the script, such that any future such cases leave a better trace in the logs to pursue.

**Comment by ecly** [comment]
I haven't been experiencing this issue recently, so I will close this and re-open should it re-occur.
