### ISSUE TITLE
Line breaks/hard return stripping

### ISSUE THREAD

**Issue by mzeidhassan** [modernmt/modernmt#544]
Hi @davidecaroselli ,
I hope all is well with you. I do hope I receive a reply from you on this one, since I am puzzled.

If I pass such text "UI strings" to the REST API, MMT strips lines breaks and concatenate all words in one sentence, which eventually renders unusable translation.

Here are sample strings:

```
Branch Code
Bank Code
Status
Line of Business 
```

Any idea how to resolve this issue? 

I tested same strings in Google Translate, Bing Translator, and Systran and they are handling them right, and consider line breaks as end of sentence.

Thanks in advance and look forward to hearing from you.

Kind regards,
Mohamed

**Comment by LoekvanKooten** [comment]
Why not simply make a function on the client side that splits this into separate lines, feeds them one by one and them glues the results back together?

**Comment by mzeidhassan** [comment]
Thanks @LoekvanKooten for your reply. 
OK, I created a web interface that calls the REST API.
In the HTML text area, I am using "white-space: pre-line;" to preserve such lines, but still MMT strips them and consider it one sentence if there is no punctuation added.

Not sure how to resolve this. If you shed more light, I would be grateful.
Thanks

**Comment by mzeidhassan** [comment]
It works if I add a period at the end of each string, but in my humble opinion, this shouldn't be the case, and MMT should consider such line breaks or hard return as an end of sentence mark.

**Comment by LoekvanKooten** [comment]
How about separating them with a preg_split on PHP_EOL and then feeding them one by one?

**Comment by LoekvanKooten** [comment]
Well, there are cases, think for example
open captions, where a hard enter does not
mean the line has ended...

**Comment by mzeidhassan** [comment]
Thanks @LoekvanKooten ! I am using Flask, but I probably can come up with something similar to PHP preg_split. 
I am trying to understand if this was intentional and why?

As for the case you mentioned, I would think this is rare, and not the norm. It's not usually the case while you write a sentence, you split it in the middle by a hard return for example.

I need to understand the logic behind this implementation.

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan !

In the latest **master** branch there is actually a commit solving this exact use case. You can now specify the `split_nl=true` parameter in the Translate API to ask ModernMT to split by newline.

However, there is still a "minimum sentence length" of 4 words per sentence (no split if the generated sentence is less than 4 words), and this is intended for improved translation quality.

If your use case is indeed the translation of a "list" of things, then @LoekvanKooten advice is definitely the best option!

**Comment by mzeidhassan** [comment]
Thank you so much @davidecaroselli for your reply. This is really great news. I appreciate it.
