### ISSUE TITLE
Adaptivity

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#546]
I have a question about the adaptivity of ModernMT. Whenever we feed new translations to ModernMT, do the weights and biases in the neural network get an actual nudge, or is the translation merely put in a database, and is the neural network used to fill up the differences of close matches from that database?

**Comment by ecly** [comment]
Just to be clear @LoekvanKooten are you referring to https://www.modernmt.com/ the translation service (which is of course based on ModernMT), or are you referring to the context memory feature of using ModernMT, the software?

**Comment by LoekvanKooten** [comment]
I'm referring to the software itself.

**Comment by ecly** [comment]
If you are using the software itself, and by adding translations you mean, adding reference translations to a context memory that you subsequently use in your GET/POST `/translate/` request then it works slightly different from your guesses.

When you use a context memory for a translation request, it will look for similar source paragraphs in the reference context memory. If any are found, it will fetch the corresponding source/reference translation pairs stored in the Kafka stream, and it will briefly "fine-tune" the underlying model. As you mention, this actually modifies the weights and biases of the neural network, albeit it only does so temporarily. When the fine-tuning has finished (this is typically a sub-second training run), then your input paragraph will be translated using the updated model, after which the model will have its weights reset to the original configuration.

Hope that was helpful, and feel free to ask if you have any additional questions,  in case I might be able to answer.

**Comment by LoekvanKooten** [comment]
Thank you for your very elaborate reply!
