### ISSUE TITLE
Changelog v4.7

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#551]
_Changelog v4.7:
Translation Memory now supports add and replace using the Translation Unit ID (parameter: tuid)._

Wasn't this already possible using PUT? (updateMemoryContent in de PHP class)? What's the difference?

**Comment by davidecaroselli** [comment]
Hi @LoekvanKooten ,

previous version allowed overwrite Translation Unit by specifying the  `old_sentence` and `old_translation` parameters, while new feature allow also to specify an id with `tuid` parameter
