### ISSUE TITLE
SSL with Rest API server

### ISSUE THREAD

**Issue by popstick** [modernmt/modernmt#575]
Is it possible to use SSL with the Rest API server? Example https://myurl.com:8045/ Can anyone point me in the right direction?

**Comment by LoekvanKooten** [comment]
There is bi such thing as SLI in neural networks: using multiple GPU's is purely for workload balancing; there is no time synchronization. 

But if your question is whether you can use multiple GPU's at once, then the answer is yes.

**Comment by popstick** [comment]
No, sorry, that's not what I mean. I'll try to explain better. 

I've set up a web client that makes a request to the Rest API to get the translation. If the website is using SSL (https) the request fails because the Rest API server doesn't use SSL.

Example: 

This works: http://naroman.club/project/
This doesn't work: https://naroman.club/project/

**Comment by LoekvanKooten** [comment]
Sorry, I need to wake up and drink my coffee first. You wrote SSL, not SLI. My bad.

**Comment by popstick** [comment]
I figured it out. It's just required an Nginx proxy.
