### ISSUE TITLE
./mmt translate --batch path/to/inputfile.en > outpufile.es not working

### ISSUE THREAD

**Issue by dominikacecylia** [modernmt/modernmt#577]
This command served previously to translate text in batch, however, the process last a few seconds now and there is no result except one line saying: © Emea 2007 chmp/spaaktywności emea/translate/in. es

The command I am using is: ./mmt translate -e emea75engine --batch /workspace/translate.es > output.pl

Appreciate any suggestions.

**Comment by davidecaroselli** [comment]
Hi @dominikacecylia 

the `translate` command takes its input in `stdin`, so the correct syntax for your command is:
```
./mmt translate -e emea75engine --batch < /workspace/translate.es > output.pl
```

**Comment by dominikacecylia** [comment]
Works, thank you :)
